<?php
/**
 * Created by PhpStorm.
 * User: leazygomalas
 * Date: 27/08/2018
 * Time: 17:12
 */

namespace App\Controller;


use App\Entity\Media;
use App\Form\MediaType;
use App\Form\VideoType;
use App\Repository\MediaRepository;
use Doctrine\Common\Persistence\ObjectManager;
use Doctrine\ORM\EntityManagerInterface;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

class MediaController extends AbstractController
{
    /**
     * Ajouter un média
     *
     * @Route("/add/media/", name="addMedia")
     */
    public function addMedia(
        Request $request,
        ObjectManager $manager
    )
    {
        $media = new Media();

        $form = $this->createForm(MediaType::class, $media);
        $form->handleRequest($request);
        if ($form->isSubmitted() && $form->isValid()) {
            // $file stores the uploaded PDF file
            /** @var Symfony\Component\HttpFoundation\File\UploadedFile $file */
            $file = $form->get('url')->getData();

            $fileName = $this->generateUniqueFileName().'.'.$file->guessExtension();

            // moves the file to the directory where media are stored
            $file->move(
                $this->getParameter('images'),
                $fileName
            );

            // updates the 'media' property to store the image file name
            // instead of its contents
            $media->setUrl($fileName);

            $media->setType('i');
            $manager->persist($media);
            $manager->flush();

            return $this->redirectToRoute('addVideo');
        }
        return $this->render(
            'Media/addMedia.html.twig', [
            'formAddMedia' => $form->createView()
        ]);
    }

    /**
     * @return string
     */
    private function generateUniqueFileName()
    {
        // md5() reduces the similarity of the file names generated by
        // uniqid(), which is based on timestamps
        return md5(uniqid());
    }

    /**
     * Ajouter une vidéo
     *
     * @Route("/add/video/", name="addVideo")
     */
    public function addVideo(
        Request $request,
        ObjectManager $manager
    )
    {
         $video = new Media();

        $form = $this->createForm(VideoType::class, $video);
        $form->handleRequest($request);
        if ($form->isSubmitted() && $form->isValid()) {

            $video->setType('v');
            $manager->persist($video);
            $manager->flush();

            $this->addFlash('success', 'Le trick a bien été ajouté!');
            return $this->redirectToRoute('homepage');
        }
        return $this->render(
            'Media/addVideo.html.twig', [
            'formAddVideo' => $form->createView()
        ]);
    }

    /**
     * Delete a media
     *
     * @Route("/delete/media/{id}", name="deletemedia")
     */
    public function removeMedia(
        $id,
        EntityManagerInterface $em
    )
    {
        $repository = $em->getRepository(Media::class);
        $media = $repository->find($id);

        $em->remove($media);
        $em->flush();

        return $this->redirectToRoute('homepage');
    }
}